HAK-114 set JDK 17
because of build failure:
Error: [ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.10.1:compile (default-compile) on project learn.github.actions: Fatal error compiling: error: invalid target release: 17